# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  kublr-api: kublr/kublr-api@dev:5
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.4

    working_directory: ~/repo

    steps:
      - checkout
      - kublr-api/auth:
          kublr-endpoint: KUBLR_ENDPOINT
          kublr-username: KUBLR_USERNAME
          kublr-password: KUBLR_PASSWORD
          insecure: true
      - run:
          name: Set variables
          command: |
            if [ -z "$CLUSTER_SPACE" ]; then
                CLUSTER_SPACE='default'
                echo "export CLUSTER_SPACE='${CLUSTER_SPACE}'" >> $BASH_ENV
                echo "/api/spaces/$CLUSTER_SPACE/cluster"
                source $BASH_ENV
            fi
      - run:
          name: Print variables
          command: |
            echo "Cluster space $CLUSTER_SPACE"
            echo "Endpoint $KUBLR_ENDPOINT"
            echo "Token $KUBLR_TOKEN"
            printenv || true
      - kublr-api/call:
          call-method: POST
          call-path: "/api/spaces/$CLUSTER_SPACE/cluster"
          call-data-file: "./k8s/cluster-spec.json"
          result-file: "cluster-result.json"
          insecure: true
      - run:
          name: Check while cluster will have Running status
          command: |
            cat cluster-result.json
            CLUSTER_SPACE=$(cat cluster-result.json | jq -r '.metadata.space')
            CLUSTER_NAME=$(cat cluster-result.json | jq -r '.metadata.name')
            CLUSTER_ID=$(cat cluster-result.json | jq -r '.id')
            echo "export CLUSTER_SPACE='${CLUSTER_ID}'" >> $BASH_ENV
            echo "export CLUSTER_NAME='${CLUSTER_ID}'" >> $BASH_ENV
            echo "export CLUSTER_NAME='${CLUSTER_ID}'" >> $BASH_ENV
            echo "Cluster id=$CLUSTER_ID space=$CLUSTER_SPACE"
            HEADERS=(-s --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Authorization: bearer '${KUBLR_TOKEN})

            echo "HEADERS=${HEADERS[@]}"

            echo "Create cluster with id $CLUSTER_ID name $CLUSTER_NAME"

            REQ_URL="$KUBLR_ENDPOINT/api/spaces/$CLUSTER_SPACE/cluster/$CLUSTER_NAME/id/$CLUSTER_ID"

            START_TIME=$(date +%s)
            TIMEOUT=900
            echo $START_TIME
            while (( "$(date +%s) - $START_TIME" < ${TIMEOUT} ))
            do
                CLUSTER_STATE=$(curl -X GET "${HEADERS[@]}" $REQ_URL| jq -r '.status.state')
                if [ "$CLUSTER_STATE" == "Running" ]; then
                    echo "Cluster is running"
                    break;
                elif [ "$CLUSTER_STATE" == "" -o "$CLUSTER_STATE" == "Creating" -o "$CLUSTER_STATE" == "Draft" ]; then
                    echo "Waiting creation, current status $CLUSTER_STATE"
                    sleep 10
                else
                    echo "Cluster state is $CLUSTER_STATE"
                    exit 1
                fi
            done
            echo "Cluster state is Ready"
      - run:
          name: Print env vars
          command: |
            echo "space=$CLUSTER_SPACE name=$CLUSTER_NAME id=$CLUSTER_ID"
      - kublr-api/get-cluster-config:
          kublr-space: $CLUSTER_SPACE
          kublr-cluster: $CLUSTER_NAME
          insecure: false
      - run:
          name: Print config
          command: |
            ls -l
            cat ./config


